"""
TS001 - Number of usual residents in households and communal establishments

Code autogenerated by UKCensusAPI
(https://github.com/virgesmith/UKCensusAPI)
"""

# This code requires an API key, see the README.md for details

# Query url:
# https://www.nomisweb.co.uk/api/v01/dataset/NM_2021_1.data.tsv?C2021_RESTYPE_3=0&MEASURES=20100&date=latest&geography=&select=GEOGRAPHY_CODE%2COBS_VALUE

import ukcensusapi.Nomisweb as CensusApi

api = CensusApi.Nomisweb("cache")
table = "TS001"
table_internal = "NM_2021_1"
query_params = {}
query_params["date"] = "latest"
query_params["select"] = "GEOGRAPHY_CODE,OBS_VALUE"
query_params["C2021_RESTYPE_3"] = "0"
query_params["MEASURES"] = "20100"
query_params["geography"] = ""
TS001 = api.get_data(table, query_params)
