# KS102EW - Age structure

# Code autogenerated by UKCensusAPI
#https://github.com/virgesmith/UKCensusAPI

# This code requires an API key, see the README.md for details
# Query url: https://www.nomisweb.co.uk/api/v01/dataset/NM_145_1.data.tsv?CELL=0&MEASURES=20100&RURAL_URBAN=0&date=latest&geography=&select=GEOGRAPHY_CODE%2COBS_VALUE

library("UKCensusAPI")
cacheDir = "cache"
api = UKCensusAPI::instance(cacheDir)
table = "KS102EW"
table_internal = "NM_145_1"
queryParams = list(
  date = "latest",
  select = "GEOGRAPHY_CODE,OBS_VALUE",
  RURAL_URBAN = "0",
  CELL = "0",
  MEASURES = "20100",
  geography = ""
)
KS102EW = UKCensusAPI::getData(api, table, queryParams)
