"""
KS102EW - Age structure

Code autogenerated by UKCensusAPI
(https://github.com/virgesmith/UKCensusAPI)
"""

# This code requires an API key, see the README.md for details

# Query url:
# https://www.nomisweb.co.uk/api/v01/dataset/NM_145_1.data.tsv?CELL=0&MEASURES=20100&RURAL_URBAN=0&date=latest&geography=&select=GEOGRAPHY_CODE%2COBS_VALUE

import ukcensusapi.Nomisweb as CensusApi

api = CensusApi.Nomisweb("cache")
table = "KS102EW"
table_internal = "NM_145_1"
query_params = {}
query_params["date"] = "latest"
query_params["select"] = "GEOGRAPHY_CODE,OBS_VALUE"
query_params["RURAL_URBAN"] = "0"
query_params["CELL"] = "0"
query_params["MEASURES"] = "20100"
query_params["geography"] = ""
KS102EW = api.get_data(table, query_params)
