"""
KS401EW - Dwellings, household spaces and accommodation type

Code autogenerated by UKCensusAPI
(https://github.com/virgesmith/UKCensusAPI)
"""

# This code requires an API key, see the README.md for details

# Query url:
# https://www.nomisweb.co.uk/api/v01/dataset/NM_618_1.data.tsv?CELL=7...13&MEASURES=20100&RURAL_URBAN=0&date=latest&geography=1249902593...1249902596%2C1249934513...1249934514&select=GEOGRAPHY_CODE%2CCELL%2COBS_VALUE

import ukcensusapi.Nomisweb as CensusApi

api = CensusApi.Nomisweb("cache")
table = "KS401EW"
table_internal = "NM_618_1"
query_params = {}
query_params["date"] = "latest"
query_params["select"] = "GEOGRAPHY_CODE,CELL,OBS_VALUE"
query_params["RURAL_URBAN"] = "0"
query_params["CELL"] = "7...13"
query_params["MEASURES"] = "20100"
query_params["geography"] = "1249902593...1249902596,1249934513...1249934514"
KS401EW = api.get_data(table, query_params)
