# TS001 - Number of usual residents in households and communal establishments

# Code autogenerated by UKCensusAPI
#https://github.com/virgesmith/UKCensusAPI

# This code requires an API key, see the README.md for details
# Query url: https://www.nomisweb.co.uk/api/v01/dataset/NM_2021_1.data.tsv?C2021_RESTYPE_3=0&MEASURES=20100&date=latest&geography=&select=GEOGRAPHY_CODE%2COBS_VALUE

library("UKCensusAPI")
cacheDir = "cache"
api = UKCensusAPI::instance(cacheDir)
table = "TS001"
table_internal = "NM_2021_1"
queryParams = list(
  date = "latest",
  select = "GEOGRAPHY_CODE,OBS_VALUE",
  C2021_RESTYPE_3 = "0",
  MEASURES = "20100",
  geography = ""
)
TS001 = UKCensusAPI::getData(api, table, queryParams)
