# TS011 - Households by deprivation dimensions

# Code autogenerated by UKCensusAPI
#https://github.com/virgesmith/UKCensusAPI

# This code requires an API key, see the README.md for details
# Query url: https://www.nomisweb.co.uk/api/v01/dataset/NM_2031_1.data.tsv?C2021_DEP_6=0...5&MEASURES=20100&date=latest&geography=&select=GEOGRAPHY_CODE%2CC2021_DEP_6%2COBS_VALUE

library("UKCensusAPI")
cacheDir = "cache"
api = UKCensusAPI::instance(cacheDir)
table = "TS011"
table_internal = "NM_2031_1"
queryParams = list(
  date = "latest",
  select = "GEOGRAPHY_CODE,C2021_DEP_6,OBS_VALUE",
  C2021_DEP_6 = "0...5",
  MEASURES = "20100",
  geography = ""
)
TS011 = UKCensusAPI::getData(api, table, queryParams)
